
[window]
opacity = 0.6
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrains Mono " }
size = 9

[cursor]
style = { shape = "Beam" , blinking = "On" }
unfocused_hollow = false

[general]
import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]
